### ISSUE TITLE
`TrustedHostsNetworkResolver` - private network IPs should not be a valid result

### ISSUE THREAD

**Issue by samdark** [yiisoft/proxy-middleware#19]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

> When choosing the X-Forwarded-For client IP address closest to the client (untrustworthy and not for security-related purposes), the first IP from the leftmost that is a valid address and **not private/internal** should be selected. ("Valid" because spoofed values may not be IP addresses at all; **"not internal/private" because clients may have used proxies on their internal network, which may have added addresses from the [private IP space](https://en.wikipedia.org/wiki/Private_network)**.)

A test cases could be:

```php
'private networks IPv4 are invalid' => [
  'remoteAddr' => '18.18.18.18',
  'trustedHosts' => [
     'hosts' => ['18.18.18.18'],
     'ipHeaders' => [[TrustedHostsNetworkResolver::IP_HEADER_TYPE_RFC7239, 'forwarded']],
  ],
  'headers' => ['forwarded' => ['for=192.168.0.1']],
  'expectedClientIp' => '18.18.18.18',
],
'private networks IPv6 are invalid' => [
  'remoteAddr' => '18.18.18.18',
  'trustedHosts' => [
     'hosts' => ['18.18.18.18'],
     'ipHeaders' => [[TrustedHostsNetworkResolver::IP_HEADER_TYPE_RFC7239, 'forwarded']],
  ],
  'headers' => ['forwarded' => ['for=fd12:3456:789a:1::1']],
  'expectedClientIp' => '18.18.18.18',
]
```

Both `192.168.0.1` and `fd12:3456:789a:1::1` are from private network so we consider these are invalid.

**Comment by arogachev** [comment]
@samdark Is it required for 1.0?

**Comment by samdark** [comment]
Yes.

**Comment by arogachev** [comment]
@samdark Does it apply to `X-Forwarded-For` only? Seems it contradicts with https://datatracker.ietf.org/doc/html/rfc7239#section-6.1:

> [6.1](https://datatracker.ietf.org/doc/html/rfc7239#section-6.1).  IPv4 and IPv6 Identifiers
> ...
> Note that the IP address may be one from the internal nets, as defined in [RFC1918](https://datatracker.ietf.org/doc/html/rfc1918) and [RFC4193](https://datatracker.ietf.org/doc/html/rfc4193).
